apiVersion: v1
kind: Secret
metadata:
  name: k8s-backend-secret
type: Opaque
data:
  # DATABASE_URL: "cG9zdGdyZXM6Ly9wb3N0Z3JlczpteVNlY3JldC9sb2NhbGhvc3Q6NTQzMg=="
  .env: "REFUQUJBU0VfVVJMPXBvc3RncmVzOi8vcG9zdGdyZXM6bXlTZWNyZXQvbG9jYWxob3N0OjU0MzIKSldUX1NFQ1JFVD1NRVNTSUAxMjMKQVdTX1NFQ1JFVF9LRVk9TVlTRUNSRVRBV1M="
